# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: ansible/centos7-ansible:latest

before_script:
  - mkdir /tmp/docker-compose
  - cp -r * /tmp/docker-compose
  - cd /tmp

syntax_check:
  stage: test
  script:
    - ansible-playbook docker-compose/tests/playbook.yml -i docker-compose/tests/inventory  --syntax-check
